### ISSUE TITLE
Setup .editorconfig, .eslintrc, .prettierrc, .styleci.yml

### ISSUE THREAD

**Issue by zhorton34** [zhorton34/vuejs-form#16]
- [ ] **.editorconfig**
```yml
root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 4
trim_trailing_whitespace = true

[*.md]
trim_trailing_whitespace = false

[*.yml]
indent_size = 2

[*.js]
indent_size = 2

```

- [ ] **.eslintrc**
```js
module.exports = {
    "env": {
        "browser": true,
        "es6": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "sourceType": "module"
    },
    "rules": {
        "indent": [
            "error",
            4
        ],
        "linebreak-style": [
            "error",
            "unix"
        ],
        "quotes": [
            "error",
            "single"
        ],
        "semi": [
            "error",
            "never"
        ]
    }
};
```

- [ ] **.prettierrc**
```json
{
    "printWidth": 80,
    "tabWidth": 2,
    "useTabs": false,
    "singleQuote": true,
    "trailingComma": "es5",
    "bracketSpacing": true,
    "jsxBracketSameLine": false,
    "semi": false,
    "requirePragma": false,
    "proseWrap": "preserve",
    "arrowParens": "avoid",

    "overrides": [
        {
            "files": "resources/css/**/*.css",
            "options": {
                "tabWidth": 2
            }
        }
    ]
}
```

- [ ] **.styleci.yml**
```yml
js:
    tab-width: 2
    use-tabs: false
    print-width: 80
    double-quotes: false
    trailing-commas: es5
    semicolons: false
    arrow-parens: avoid
    bracket-spacing: true
    finder:
        exclude:
            - build
            - dist
            - node_modules
        name:
            - '*.js'
            - '*.jsx'
        not-name:
            - '*.min.js'
```
